"""
Ed25519 cryptographic operations for NEXLINK.

This module provides Ed25519 signature verification that is compatible with:
- Rust agent (ed25519-dalek)
- Node.js backend (@noble/ed25519)

All signatures and public keys are hex-encoded strings.
"""

import hashlib
from typing import Optional
from nacl.signing import VerifyKey
from nacl.exceptions import BadSignatureError
import structlog

logger = structlog.get_logger()


class Ed25519Error(Exception):
    """Base exception for Ed25519 operations."""
    pass


class InvalidSignatureError(Ed25519Error):
    """Raised when signature verification fails."""
    pass


class InvalidPublicKeyError(Ed25519Error):
    """Raised when public key is invalid."""
    pass


def hex_to_bytes(hex_string: str) -> bytes:
    """
    Convert hex string to bytes.
    
    Args:
        hex_string: Hex-encoded string (with or without '0x' prefix)
        
    Returns:
        Bytes representation
        
    Raises:
        ValueError: If hex string is invalid
    """
    # Remove '0x' prefix if present
    if hex_string.startswith('0x'):
        hex_string = hex_string[2:]
    
    # Ensure even length
    if len(hex_string) % 2 != 0:
        raise ValueError(f"Hex string has odd length: {len(hex_string)}")
    
    try:
        return bytes.fromhex(hex_string)
    except ValueError as e:
        raise ValueError(f"Invalid hex string: {e}")


def bytes_to_hex(data: bytes) -> str:
    """
    Convert bytes to hex string.
    
    Args:
        data: Bytes to convert
        
    Returns:
        Hex-encoded string (lowercase, no prefix)
    """
    return data.hex()


def verify_ed25519_signature(
    message: bytes,
    signature_hex: str,
    public_key_hex: str
) -> bool:
    """
    Verify an Ed25519 signature.
    
    This function verifies signatures generated by the Rust NEXLINK Agent
    (ed25519-dalek) and is compatible with the Node.js backend (@noble/ed25519).
    
    Args:
        message: The message that was signed (as bytes)
        signature_hex: Hex-encoded signature (64 bytes = 128 hex chars)
        public_key_hex: Hex-encoded public key (32 bytes = 64 hex chars)
        
    Returns:
        True if signature is valid, False otherwise
        
    Raises:
        InvalidPublicKeyError: If public key is invalid
        InvalidSignatureError: If signature format is invalid
        
    Note:
        This function does NOT raise exceptions for invalid signatures.
        It returns False for any verification failure.
        Exceptions are only raised for malformed inputs.
    """
    try:
        # Validate signature length (64 bytes = 128 hex chars)
        if len(signature_hex) != 128:
            logger.warning(
                "Invalid signature length",
                expected=128,
                actual=len(signature_hex)
            )
            return False
        
        # Validate public key length (32 bytes = 64 hex chars)
        if len(public_key_hex) != 64:
            logger.warning(
                "Invalid public key length",
                expected=64,
                actual=len(public_key_hex)
            )
            return False
        
        # Convert hex to bytes
        signature_bytes = hex_to_bytes(signature_hex)
        public_key_bytes = hex_to_bytes(public_key_hex)
        
        # Create VerifyKey from public key bytes
        verify_key = VerifyKey(public_key_bytes)
        
        # Verify signature
        # PyNaCl's verify() raises BadSignatureError if invalid
        verify_key.verify(message, signature_bytes)
        
        logger.debug("Ed25519 signature verification successful")
        return True
        
    except BadSignatureError:
        logger.debug("Ed25519 signature verification failed: invalid signature")
        return False
        
    except ValueError as e:
        logger.warning("Invalid hex encoding", error=str(e))
        return False
        
    except Exception as e:
        logger.error("Unexpected error during signature verification", error=str(e))
        return False


def verify_challenge_proof(
    challenge: str,
    signature_hex: str,
    public_key_hex: str
) -> bool:
    """
    Verify a challenge-response proof.
    
    The proof is: Sign(private_key, challenge)
    We verify: Verify(public_key, challenge, signature)
    
    Args:
        challenge: The challenge string that was signed
        signature_hex: Hex-encoded signature
        public_key_hex: Hex-encoded public key
        
    Returns:
        True if signature is valid, False otherwise
    """
    # Convert challenge string to bytes (UTF-8)
    message = challenge.encode('utf-8')
    
    return verify_ed25519_signature(message, signature_hex, public_key_hex)


def verify_enrollment_proof(
    device_id: str,
    timestamp: int,
    signature_hex: str,
    public_key_hex: str
) -> bool:
    """
    Verify an enrollment proof.
    
    The enrollment proof signs: f"{device_id}:{timestamp}"
    
    Args:
        device_id: Device identifier
        timestamp: Unix timestamp
        signature_hex: Hex-encoded signature
        public_key_hex: Hex-encoded public key
        
    Returns:
        True if signature is valid, False otherwise
    """
    # Construct the message exactly as the Rust agent does
    message = f"{device_id}:{timestamp}".encode('utf-8')
    
    return verify_ed25519_signature(message, signature_hex, public_key_hex)


def generate_challenge(length: int = 32) -> str:
    """
    Generate a cryptographically secure random challenge.
    
    Args:
        length: Number of random bytes (default 32 = 256 bits)
        
    Returns:
        Hex-encoded challenge string
    """
    import secrets
    challenge_bytes = secrets.token_bytes(length)
    return bytes_to_hex(challenge_bytes)


def hash_password(password: str) -> str:
    """
    Hash a password using SHA-256.
    
    Note: For actual password storage, use bcrypt via passlib.
    This is only for challenge-response hashing if needed.
    
    Args:
        password: Password to hash
        
    Returns:
        Hex-encoded SHA-256 hash
    """
    return hashlib.sha256(password.encode('utf-8')).hexdigest()
